# Variational autoencoder
This notebook will investiga

In [1]:
%matplotlib
import numpy as np
import numpy.random as rnd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras

import pandas as pd
import seaborn as sns
from collections import defaultdict

from models.variational_autoencoder import VariationalAutoencoder
from models.autoencoder import Autoencoder
from models.continuous_bernoulli_loss import continuous_bernoulli_loss

# For dimension reduction
from sklearn.manifold import TSNE
from sklearn.decomposition import PCA

# for visualization and evaluation
from visual.latent_plane_mosaic import LatentPlaneMosaic
from visual.latent_interpolation_mosaic import LatentInterpolationMosaic
from visual.sample_scatter_gui import SampleScatterGUI

Using matplotlib backend: Qt5Agg

In [2]:
model_df = pd.DataFrame(data = {
    'path' : ["models\\saved\\ae", "models\\saved\\vae_10", "models\\saved\\vae_100" , "models\\saved\\vae_1000"],
    'ae_type' : ['ae', 'vae', 'vae', 'vae'],
    },
    index = ['ae', 'vae_10', 'vae_100', 'vae_1000'],
)

In [3]:
models = []
for name, model in model_df.iterrows():
    if model['ae_type'] == "ae":
        models.append(keras.models.load_model(model['path'], 
                         custom_objects={"Autoencoder": Autoencoder,
                                         "continuous_bernoulli_loss": continuous_bernoulli_loss}))
    elif model['ae_type'] == "vae":
        models.append(keras.models.load_model(model['path'], 
                                 custom_objects={"VariationalAutoencoder": VariationalAutoencoder,
                                                 "continuous_bernoulli_loss":  continuous_bernoulli_loss}))
model_df['model'] = models

In [4]:
num_models = model_df.shape[0]
latent_dim = 10

In [5]:
model_df.head()

,path,ae_type,model
ae,models\saved\ae,ae,<models.autoencoder.Autoencoder object at 0x00...
vae_10,models\saved\vae_10,vae,<models.variational_autoencoder.VariationalAut...
vae_100,models\saved\vae_100,vae,<models.variational_autoencoder.VariationalAut...
vae_1000,models\saved\vae_1000,vae,<models.variational_autoencoder.VariationalAut...

## Preprocess data

In [6]:
(_, _), (test_digits, test_labels) = keras.datasets.mnist.load_data()
test_digits = np.expand_dims(test_digits, -1).astype("float32") / 255
input_shape = test_digits.shape[1:]
num_test = test_labels.shape[0]

## Load Variational autoencoder

### Print setup details

## Reconstruct and dimension reductions

In [7]:
# Fill
latent_df_list = []
latent_dim_df_list = []

model_map = defaultdict(list)


for name, model in model_df.iterrows():
    if model['ae_type'] == "ae":
        code = model['model'].encoder(test_digits).numpy()
        code_std = np.empty(shape = code.shape)*np.nan
        
    elif model['ae_type'] == "vae":
        digit_distribution = model['model'].encoder(test_digits).numpy()
        code = digit_distribution[:,0,:]
        code_std = np.sqrt(np.exp(digit_distribution[:,1,:]))
    
    code_distance = np.linalg.norm(code, axis = 1)
    code_radius = np.power(np.prod(code_std, axis = 1),1/latent_dim)
    code_loss = tf.reduce_mean(tf.reduce_mean(tf.keras.losses.binary_crossentropy(test_digits, model['model'](test_digits)),axis = -1),axis = -1).numpy()
    print(code_loss.shape)
    code_tsne = TSNE(n_components = 2).fit_transform(code)
    
    _latent_df = pd.DataFrame(data = {
        'model_name' : name,
        'label' : test_labels,
        'loss' : code_loss,
        'distance' : code_distance,
        'radius' : code_radius,
        'tsne_0' : code_tsne[:,0],
        'tsne_1' : code_tsne[:,1],
    })
    latent_df_list.append(_latent_df)
    #_latent_df = pd.DataFrame(data = name, columns = ["model_name"], index = range(num_test))
    #_latent_df['label'] = test_labels
    #_latent_df['distance'] = mean_distance
    #_latent_df[["latent_"+str(i) for i in range(latent_dim)]] = code
    #_latent_df[["latent_std_"+str(i) for i in range(latent_dim)]] = code_std
    #_latent_df[['tsne_0', 'tsne_1']] = code_tsne
    #df_list.append(temp_df)
    
    latent_dim_labels = test_labels.repeat(repeats = latent_dim)
    latent_dim_digit_index = np.arange(num_test).repeat(repeats = latent_dim)
    latent_dim_dim_index = np.tile(np.arange(latent_dim), num_test)
    latent_dim_value = code.reshape(-1)
    latent_dim_std = code_std.reshape(-1)
    
    _latent_dim_df = pd.DataFrame(data = {
        'model_name' : name,
        'label' : latent_dim_labels,
        'digit_index' : latent_dim_digit_index,
        'dim_index' : latent_dim_dim_index,
        'value' : latent_dim_value,
        'std' : latent_dim_std
    })
    
    latent_dim_df_list.append(_latent_dim_df)
    
    
    # Calculate global code information
    model_map['latent_point_mean'].append(np.mean(code, axis = 0))
    model_map['latent_point_std'].append(np.std(code, axis = 0))
    model_map['latent_spread_mean'].append(np.mean(code_std, axis = 0))
    model_map['latent_spread_std'].append(np.std(code_std, axis = 0))

        
latent_df = pd.concat(latent_df_list)
latent_dim_df = pd.concat(latent_dim_df_list)

model_df = pd.concat([model_df, pd.DataFrame(data = model_map)])
#model_df['latent_mean'] = latent_mean_list
#model_df['latent_std'] = latent_std_list
#model_df['latent_base'] = latent_base_list

(10000,)
(10000,)
(10000,)
(10000,)

## Investigation

### Show reconstructions

In [8]:
latent_df.head()

  model_name  label      loss   distance  radius     tsne_0     tsne_1
0         ae      7  0.070490  15.820858     NaN   7.174412 -66.232681
1         ae      2  0.117689   9.960896     NaN -28.950567  13.771372
2         ae      1  0.038200  24.145765     NaN  74.452095 -31.667559
3         ae      0  0.096915   8.166095     NaN  33.432430  49.826084
4         ae      4  0.084998  14.815680     NaN -66.062698 -27.214878

In [34]:
latent_mean_df = latent_dim_df.groupby(by = ['model_name', 'dim_index'],as_index = False).mean()
latent_std_df = latent_dim_df.groupby(by = ['model_name', 'dim_index'],as_index = False).std()

In [36]:
latent_mean_df

   model_name  dim_index   label  digit_index     value       std
0          ae          0  4.4434       4999.5 -1.309089       NaN
1          ae          1  4.4434       4999.5  0.659992       NaN
2          ae          2  4.4434       4999.5  1.053212       NaN
3          ae          3  4.4434       4999.5  3.870928       NaN
4          ae          4  4.4434       4999.5  2.164852       NaN
5          ae          5  4.4434       4999.5 -1.736220       NaN
6          ae          6  4.4434       4999.5 -4.379542       NaN
7          ae          7  4.4434       4999.5 -1.824523       NaN
8          ae          8  4.4434       4999.5 -2.629080       NaN
9          ae          9  4.4434       4999.5 -1.746778       NaN
10     vae_10          0  4.4434       4999.5  0.042709  0.345161
11     vae_10          1  4.4434       4999.5 -0.026465  0.374123
12     vae_10          2  4.4434       4999.5 -0.015514  0.994776
13     vae_10          3  4.4434       4999.5  0.008959  0.997678
14     vae_10          4  4.4434       4999.5  0.007569  0.992662
15     vae_10          5  4.4434       4999.5 -0.005508  0.991194
16     vae_10          6  4.4434       4999.5 -0.011866  0.995828
17     vae_10          7  4.4434       4999.5  0.000237  0.995950
18     vae_10          8  4.4434       4999.5 -0.008287  0.990243
19     vae_10          9  4.4434       4999.5  0.052660  0.191176
20    vae_100          0  4.4434       4999.5  0.053342  0.864569
21    vae_100          1  4.4434       4999.5 -0.013476  0.059753
22    vae_100          2  4.4434       4999.5  0.066571  0.084304
23    vae_100          3  4.4434       4999.5  0.049720  0.097191
24    vae_100          4  4.4434       4999.5 -0.079448  0.128352
25    vae_100          5  4.4434       4999.5  0.022777  0.918245
26    vae_100          6  4.4434       4999.5 -0.023753  0.958202
27    vae_100          7  4.4434       4999.5  0.037389  0.971026
28    vae_100          8  4.4434       4999.5 -0.085432  0.179726
29    vae_100          9  4.4434       4999.5 -0.011536  0.081826
30   vae_1000          0  4.4434       4999.5  0.330648  0.026523
31   vae_1000          1  4.4434       4999.5  0.213255  0.035853
32   vae_1000          2  4.4434       4999.5 -0.307546  0.038197
33   vae_1000          3  4.4434       4999.5  0.015938  0.036988
34   vae_1000          4  4.4434       4999.5 -0.447926  0.034444
35   vae_1000          5  4.4434       4999.5 -0.080598  0.035188
36   vae_1000          6  4.4434       4999.5 -0.258613  0.031772
37   vae_1000          7  4.4434       4999.5 -0.009935  0.029731
38   vae_1000          8  4.4434       4999.5  0.205682  0.030342
39   vae_1000          9  4.4434       4999.5  0.456446  0.028564

In [10]:
latent_dim_df.head()

  model_name  label  digit_index  dim_index     value  std
0         ae      7            0          0  8.920861  NaN
1         ae      7            0          1  2.935239  NaN
2         ae      7            0          2  0.101040  NaN
3         ae      7            0          3  3.835251  NaN
4         ae      7            0          4  5.167331  NaN

In [103]:
num_col = 4
num_row = 3
num_img = num_row*num_col
rec_index = rnd.randint(num_test,size =(num_row*num_col,) )
digits = test_digits
digits = digits[rec_index]

In [104]:

model = model_df.loc['ae','model']

reconstructions = model(digits)
i = 0
for col in range(num_col):
    for row in range(num_row): 
        pair = np.concatenate((digits[i], reconstructions[i]), axis = 1)
        if row == 0: 
            ver_img = pair
        else:
            ver_img = np.concatenate((ver_img,
                                 pair), axis = 0)
        i = i + 1
    if col == 0:
        img = ver_img
    else: 
        img = np.concatenate((img,
                              ver_img), axis = 1)

sns.heatmap(img[:,:,0], vmin=0, vmax = 1)

In [105]:

num_dig = 14
rec_index = rnd.randint(num_test,size =(num_dig,) )
digits = test_digits
digits = digits[rec_index]

reconstructions = []
for name, model in model_df.iterrows():
    reconstructions.append(model['model'](digits))

for dig_i in range(num_dig):
    rec_im = digits[dig_i]
    model_i = 0
    for name, model in model_df.iterrows():
        
        rec_im = np.concatenate((rec_im,
                         reconstructions[model_i][dig_i]),
                         axis = 0)
        model_i = model_i + 1
    if dig_i == 0:
        im = rec_im
    else:
        im = np.concatenate((im, rec_im), axis = 1)
    
sns.heatmap(im[:,:,0], vmin=0, vmax = 1)

### Latent

In [106]:

indeces = rnd.randint(num_test,size = (3,))
indeces = [1,2,3]
ul = test_digits[indeces[0]]
ur = test_digits[indeces[1]]
dl = test_digits[indeces[2]]
z =  np.zeros(dl.shape)
corner_image = np.concatenate( (np.concatenate((ul,ur),axis = 1),
                                np.concatenate((dl,z ),axis = 1)), axis = 0)

In [107]:

model = model_df.loc['vae_10','model']
mosaic = LatentInterpolationMosaic(
                          model.encode,
                          model.decoder,
                          test_digits,
                          indeces,
                          num_row = 15,
                          num_col = 15).mosaic



sns.heatmap(mosaic[:,:,0], vmin = 0, vmax = 1)

### Scatter

In [108]:
model_name = 'vae_1000'
scatter = latent_df[latent_df['model_name']==model_name][['tsne_0', 'tsne_1']].to_numpy()
SampleScatterGUI(scatter, test_labels, test_digits)

In [109]:
model_name = "vae_1000"
sns.jointplot(data = latent_df[latent_df['model_name'] == model_name ], x = 'tsne_0', y = 'tsne_1',
              hue = 'label',
              palette = 'colorblind')

In [110]:
model_name = "vae_1000"
sns.relplot(data = latent_df[latent_df['model_name'] == model_name ], x = 'tsne_0', y = 'tsne_1',
              hue = 'label',
              palette = 'colorblind',
           kind = 'scatter')

### Spread

Here we have that the first 6 principal axises are almost one and the remaining 4 are almost zero (e-3). This is combination with that the cross covariance seem to be super much zero (e-15), indicates that we have a six dimesnioal sphere in this ten dimesional latent space. Interesting to see is also if you create a latent vector in the pca-vector space. Then comparing the latent value in each dimension times the spread in each dimension, gives you the importance of that dimension in that latent point. A low importance will not have an effect on the output (kind of like a low derivative...), while a hight value will give a big difference.

In [111]:
axis_index = [0,-1]
scaling_factors = np.array([2,2])

In [112]:
model_name = 'ae'
model = model_df.loc[model_name, 'model']
latent_vectors = model_df.loc[model_name, 'latent_base'][axis_index]
latent_origin  = model_df.loc[model_name, 'latent_mean']
mosaic = LatentPlaneMosaic(model.decoder,
                  latent_vectors = (scaling_factors*latent_vectors.T).T,
                  latent_origin = latent_origin,
                  num_row = 20,
                  num_col = 20).mosaic

#fig,ax = plt.subplots(1,1)
#ax.imshow(mosaic)
sns.heatmap(mosaic[:,:,0], vmin = 0, vmax = 1)

KeyError: 'latent_base'

## Spred

In [113]:
## TODO
# Make a grid work with seaborn to plot the things nice
# Maybe do a pca on the

In [117]:
latent_dim_df.head()

  model_name  label  digit_index     value  std
0         ae      7            0  8.920861  NaN
1         ae      7            0  2.935239  NaN
2         ae      7            0  0.101040  NaN
3         ae      7            0  3.835251  NaN
4         ae      7            0  5.167331  NaN

In [115]:
sns.catplot(data = latent_df.query("model_name != 'ae'"), x = 'label',y = 'distance', col = 'model_name', kind = 'violin' )

In [122]:
sns.catplot(data= latent_df,
            x = "model_name", y = 'distance',
            kind =  'violin')

In [61]:
sns.relplot(data = latent_df,
            x = 'latent_8',
            y = 'latent_std_8',
           hue = 'model_name')

In [21]:
sns.displot(data = latent_dim_df,
            x = 'value',
            hue = 'model_name',
            col = 'dim_index',
            col_wrap = 5,
           kind = 'kde',
           log_scale = True)

C:\Users\joelw\anaconda3\lib\site-packages\pandas\core\arraylike.py:358: RuntimeWarning: invalid value encountered in log10
  result = getattr(ufunc, method)(*inputs, **kwargs)

In [11]:
gd = latent_df.groupby(by = 'model_name')
gd.mean()

             label      loss   distance        volume    tsne_0    tsne_1
model_name
ae          4.4434  0.107484  11.528251           NaN  0.650591  0.080218
vae_10      4.4434  0.176434   1.550688  2.520912e-02  0.685955 -0.116369
vae_100     4.4434  0.126766   2.398272  2.634881e-06 -0.407366  0.574472
vae_1000    4.4434  0.109711   3.335280  7.913443e-14  0.033955  0.278838

In [63]:
sns.set()
values = ['latent_std_'+str(i) for i in range(0,3)]
rows = len(values)
fig, axs = plt.subplots(rows,4, sharey = False, sharex = False)
fig.suptitle("Best title")
for row in range(rows):
    col = 0
    for name, model in model_df.iterrows():
        ax = axs[row,col]
        col = col+1
        sns.histplot(latent_df[latent_df['model_name']== name], x=values[row],
                     ax = ax,
                     binrange = (0,1.1))

In [64]:
sns.set()
values = ['latent_'+str(i) for i in range(0,3)]
rows = len(values)
fig, axs = plt.subplots(rows,4, sharey = False, sharex = False)
fig.suptitle("Best title")
for row in range(rows):
    col = 0
    for name, model in model_df.iterrows():
        ax = axs[row,col]
        col = col+1
        sns.histplot(latent_df[latent_df['model_name']== name], x=values[row], ax = ax)

In [12]:
latent_df.head()

  model_name  label      loss   distance  volume     tsne_0     tsne_1
0         ae      7  0.070490  15.820858     NaN   0.828527 -65.579109
1         ae      2  0.117689   9.960896     NaN  38.527561   0.520172
2         ae      1  0.038200  24.145765     NaN  54.537647 -52.660400
3         ae      0  0.096915   8.166095     NaN -13.989736  54.813965
4         ae      4  0.084998  14.815680     NaN -68.326767 -24.577076

In [45]:
sns.displot(data = latent_df, x = 'loss', hue = 'model_name', kind = 'kde')

In [47]:
sns.displot(data = latent_df, x = 'distance',hue = 'model_name', kind = 'kde')

In [48]:
sns.displot(data = latent_df, x = 'radius',hue = 'model_name', kind = 'kde')

C:\Users\joelw\anaconda3\lib\site-packages\seaborn\distributions.py:306: UserWarning: Dataset has 0 variance; skipping density estimate.
  warnings.warn(msg, UserWarning)

In [49]:
######### IMPORTANT ########
sns.relplot(x = latent_mean_df['std'], y = latent_std_df['value'], hue = latent_mean_df['model_name'])

In [33]:
ssns.relplot(data = latent_dim_df,
           x = 'value',
           y = 'std',
           col = 'dim_index',
           col_wrap = 4,
           hue = 'model_name')

                       label  digit_index     value       std
model_name dim_index
ae         0          4.4434       4999.5 -1.309089       NaN
           1          4.4434       4999.5  0.659992       NaN
           2          4.4434       4999.5  1.053212       NaN
           3          4.4434       4999.5  3.870928       NaN
           4          4.4434       4999.5  2.164852       NaN
           5          4.4434       4999.5 -1.736220       NaN
           6          4.4434       4999.5 -4.379542       NaN
           7          4.4434       4999.5 -1.824523       NaN
           8          4.4434       4999.5 -2.629080       NaN
           9          4.4434       4999.5 -1.746778       NaN
vae_10     0          4.4434       4999.5  0.042709  0.345161
           1          4.4434       4999.5 -0.026465  0.374123
           2          4.4434       4999.5 -0.015514  0.994776
           3          4.4434       4999.5  0.008959  0.997678
           4          4.4434       4999.5  0.007569  0.992662
           5          4.4434       4999.5 -0.005508  0.991194
           6          4.4434       4999.5 -0.011866  0.995828
           7          4.4434       4999.5  0.000237  0.995950
           8          4.4434       4999.5 -0.008287  0.990243
           9          4.4434       4999.5  0.052660  0.191176
vae_100    0          4.4434       4999.5  0.053342  0.864569
           1          4.4434       4999.5 -0.013476  0.059753
           2          4.4434       4999.5  0.066571  0.084304
           3          4.4434       4999.5  0.049720  0.097191
           4          4.4434       4999.5 -0.079448  0.128352
           5          4.4434       4999.5  0.022777  0.918245
           6          4.4434       4999.5 -0.023753  0.958202
           7          4.4434       4999.5  0.037389  0.971026
           8          4.4434       4999.5 -0.085432  0.179726
           9          4.4434       4999.5 -0.011536  0.081826
vae_1000   0          4.4434       4999.5  0.330648  0.026523
           1          4.4434       4999.5  0.213255  0.035853
           2          4.4434       4999.5 -0.307546  0.038197
           3          4.4434       4999.5  0.015938  0.036988
           4          4.4434       4999.5 -0.447926  0.034444
           5          4.4434       4999.5 -0.080598  0.035188
           6          4.4434       4999.5 -0.258613  0.031772
           7          4.4434       4999.5 -0.009935  0.029731
           8          4.4434       4999.5  0.205682  0.030342
           9          4.4434       4999.5  0.456446  0.028564

## Generative power

In [66]:
model_name = 'ae'
mean = np.zeros(latent_dim)
mean = model_df.loc[model_name,'latent_mean']
cov  = 1*np.eye(latent_dim)
num_col = 15
num_row = 10
num_img = num_row*num_col
latent_points = rnd.multivariate_normal(mean, cov, size = (num_img))

In [67]:
model = model_df.loc[model_name, 'model']
title = "Reconstruction with autoencoder"
fig, ax = plt.subplots()
reconstructions = model.decoder(latent_points)
i = 0
for col in range(num_col):
    for row in range(num_row): 
        if row == 0: 
            ver_img = reconstructions[i]
        else:
            ver_img = np.concatenate((ver_img,
                                 reconstructions[i]), axis = 0)
        i = i + 1
    if col == 0:
        img = ver_img
    else: 
        img = np.concatenate((img,
                              ver_img), axis = 1)
sns.heatmap(img[:,:,0])

In [68]:
mean = np.zeros(latent_dim)
cov  = 1*np.eye(latent_dim)
num_dig = 5
latent_points = rnd.multivariate_normal(mean, cov, size = (num_dig))

reconstructions = []
for name, model in model_df.iterrows():
    reconstructions.append(model['model'].decoder(latent_points))
    
fig, axs = plt.subplots(num_models, num_dig, sharex = True, sharey = True)
for model_i in range(num_models):
    for dig_i in range(num_dig):
        ax = axs[model_i, dig_i]
        sns.heatmap(reconstructions[model_i][dig_i][:,:,0], ax = ax)

array([ 0.04270896, -0.02646526, -0.01551382,  0.00895875,  0.00756909,
       -0.00550758, -0.01186571,  0.00023721, -0.0082873 ,  0.0526603 ],
      dtype=float32)